### ISSUE TITLE
Update button

### ISSUE THREAD

**Issue by afrikhero** [mdn/express-locallibrary-tutorial#38]
There seems to be an error on the MDN resource below in the book update field. The information below shows after I updated the exports.book_update_post function. I noticed there is a slight difference between the content of the function on the github repo and the function in the MDN page. The repo code works fine. Can you update the MDN page? 
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms 

    body('title', 'Title must not be empty.').isLength({ min: 1 }).trim(),
    ^

/home/afrikhero/grive/local-library/controllers/bookController.js:250

ReferenceError: body is not defined
    at Object.<anonymous> (/home/afrikhero/grive/local-library/controllers/bookController.js:250:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/afrikhero/grive/local-library/routes/catalog.js:5:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by hamishwillee** [comment]
There may be trivial differences, but they shouldn't cause this error. Have you got these two lines at the top of your controller file? 
```
const { body,validationResult } = require('express-validator/check');
const { sanitizeBody } = require('express-validator/filter');
```

**Comment by afrikhero** [comment]
Hi Hamishwillee,
Thanks for the heads up. That fixed everything for me.

**Comment by hamishwillee** [comment]
You're welcome. I'll close this then, because that is documented in the guide.
