### ISSUE TITLE
Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

### ISSUE THREAD

**Issue by gadielkalleb** [mdn/express-locallibrary-tutorial#42]
// DISPLAY DETAIL PAGE FOR A SPECIFIC genre
exports.genre_detail = function (req, res, next) {
    var id = mongoose.Types.ObjectId(req.params.id);

    async.parallel({
        genre: function (callback) {
            Genre.findById(id)
                .exec(callback);
        },

        genre_books: function (callback) {
            Book.find({
                    'genre': id
                })
                .exec(callback);
        },

    }, function (err, results) {
        if (err) {
            console.log(req.params.id);
            return next(err);
        }
        if (results.genre == null) { // No results.
            var err = new Error('Genre not found');
            err.status = 404;
            return next(err);
        }
        // Successful, so render.
        res.render('genre_detail', {
            title: 'Genre Detail',
            genre: results.genre,
            genre_books: results.genre_books
            
        });
    });

};

Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/bson/lib/bson/objectid.js:50:11)
    at ObjectID (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/bson/lib/bson/objectid.js:31:42)
    at exports.genre_detail (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/controllers/genreController.js:28:29)
    at Layer.handle [as handle_request] (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/express/lib/router/layer.js:95:5)
    at /home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/express/lib/router/index.js:281:22
    at param (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/express/lib/router/index.js:354:14)
    at param (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/express/lib/router/index.js:410:3)
    at next (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/express/lib/router/index.js:174:3)
    at router (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/kalleb/Documentos/projetos-javascript/express-locallibrary-tutorial/node_modules/express/lib/router/index.js:317:13)

**Comment by ngminhtrung** [comment]
I encountered the same issue. Have not figured out what the solution is.

**Comment by hamishwillee** [comment]
Do you get this using exactly this example and package.json, or is the problem when you create your own version? I will try this again late this week.

**Comment by gadielkalleb** [comment]
Yesterday I removed Node.js. I installed it again. For even the base project in the git hub did not work. Apparently it's working, without the var id = mogoose.Types.ObjectId (req.params.id)

**Comment by gadielkalleb** [comment]
My node was in version 6.12.1, if I'm not mistaken. I used to update all my packages, I'm with version 8.1.4 of the node now

**Comment by VaibhavAjayGupta** [comment]
@gadielkalleb @ngminhtrung 
An ObjectId is a 12-byte structure.
Protocol to use mongoose.Types.ObjectId(str) => str must be of 12 bytes or 24 charcter hex string exactly. It will give the mentioned error if any the criteria not met.
You must be inputing your custom ids it works fine with default ids.
Only strings of exact length 12 or hex strings of exact length 24 are valid to use with mongoose.Types.ObjectId(str).

**Comment by gadielkalleb** [comment]
after reinstalling the node and dependencies, worked up to the tutorial example.
it should probably be something on the node.
apparently everything is working now.

**Comment by hamishwillee** [comment]
Great! I will close this then.

**Comment by shivarajsb** [comment]
Figured out what the issue was, I was passing in a hex string of length 23, the required string length is 24. Please check if that's the case @VaibhavAjayGupta, that was really helpful. Thanks 👍

**Comment by whoafridi** [comment]
> Figured out what the issue was, I was passing in a hex string of length 23, the required string length is 24. Please check if that's the case @VaibhavAjayGupta, that was really helpful. Thanks +1

how do i find that my one is 23 or 23 hex?

**Comment by Abhishekkumar4444** [comment]
I am also getting the same issue while  using (  findByIdAndUpdate   ) and performing  crud  operation in expressjs .

**Comment by hamishwillee** [comment]
Please don't necrobump. IF there is an error in this example we can fix it, but you should post it as a new issue with enough information to allow us to help you debug. If it is an error in your own code, then perhaps a better place to raise questions is the support forum.
