### ISSUE TITLE
Getting the following errors when i am trying to run node populate mongodb 

### ISSUE THREAD

**Issue by ZubierAbd** [mdn/express-locallibrary-tutorial#52]
DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
MongoDB connection error: { MongoNetworkError: failed to connect to server [ds121183.mlab.com:21183] on first connect [MongoNetworkError: connect ETIMEDOUT 52.90.44.246:21183]

**Comment by hamishwillee** [comment]
@roopegarcia For now you can ignore that. I will be reviewing and updating the examples in the coming months.

We connect to MongoDb via Mongoose. I suspect that to fix this we will just need to update to a more recent Mongoose. Won't know until I've tried it.

**Comment by hamishwillee** [comment]
Sorry for delay. This is imply fixed by connecting mongoose like this : `mongoose.connect(mongoDB`**, { useNewUrlParser: true** `});`

**Comment by kidaqrus** [comment]
it is still not working

**Comment by kidaqrus** [comment]
help me fix this please

C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial>node populatedb 'mongodb+srv://kidaqrus:adikwu1111@cluster0-mbdj7.mongodb.net/local_library?retryWrites=true'
This script populates some test books, authors, genres and bookinstances to your database. Specified database as argument - e.g.: populatedb mongodb+srv://cooluser:coolpassword@cluster0-mbdj7.mongodb.net/local_library?retryWrites=true
MongoDB connection error: TypeError: Cannot read property 'split' of null
    at parseSrvConnectionString (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongodb-core\lib\uri_parser.js:40:23)
    at parseConnectionString (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongodb-core\lib\uri_parser.js:514:12)
    at connect (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongodb\lib\operations\mongo_client_ops.js:195:3)
    at connectOp (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongodb\lib\operations\mongo_client_ops.js:284:3)
    at executeOperation (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongodb\lib\utils.js:416:24)
    at MongoClient.connect (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongodb\lib\mongo_client.js:175:10)
    at Promise (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongoose\lib\connection.js:612:12)
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongoose\lib\connection.js:609:19)
    at Mongoose.connect (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongoose\lib\index.js:321:15)
    at Object.<anonymous> (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\populatedb.js:22:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
(node:17804) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of null
    at parseSrvConnectionString (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongodb-core\lib\uri_parser.js:40:23)
    at parseConnectionString (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongodb-core\lib\uri_parser.js:514:12)
    at connect (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongodb\lib\operations\mongo_client_ops.js:195:3)
    at connectOp (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongodb\lib\operations\mongo_client_ops.js:284:3)
    at executeOperation (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongodb\lib\utils.js:416:24)
    at MongoClient.connect (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongodb\lib\mongo_client.js:175:10)
    at Promise (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongoose\lib\connection.js:612:12)
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongoose\lib\connection.js:609:19)
    at Mongoose.connect (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\node_modules\mongoose\lib\index.js:321:15)
    at Object.<anonymous> (C:\Users\kidaqrus\EXPRESSFILES\express-locallibrary-tutorial\populatedb.js:22:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
(node:17804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:17804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
