### ISSUE TITLE
Error: Route.get() requires a callback function but got a [object Undefined]

### ISSUE THREAD

**Issue by campgurus** [mdn/express-locallibrary-tutorial#58]
after adding routes/catalog.js

trace below:
```
/Users/dariusgoore/development/express-locallibrary-tutorial/node_modules/express/lib/router/route.js:202
        throw new Error(msg);
        ^

Error: Route.get() requires a callback function but got a [object Undefined]
    at Route.(anonymous function) [as get] (/Users/dariusgoore/development/express-locallibrary-tutorial/node_modules/express/lib/router/route.js:202:15)
    at Function.proto.(anonymous function) [as get] (/Users/dariusgoore/development/express-locallibrary-tutorial/node_modules/express/lib/router/index.js:510:19)
    at Object.<anonymous> (/Users/dariusgoore/development/express-locallibrary-tutorial/routes/catalog.js:86:8)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/dariusgoore/development/express-locallibrary-tutorial/app.js:9:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by hamishwillee** [comment]
I do not get this problem after adding the file - following the instructions rigorously. Also this example works/builds. 

It is mostly likely that there is some syntax error in your catalog.js. To debug this I'd start by creating a very minimal version of catalog.js and see where it fails. 

As this is several months old I am closing. If you still have the same problem, then suggest you try debugging as above. If that doesn't work reopen and attach a link to repo/branch showing the problem.
