### ISSUE TITLE
Schema hasn't been registered for model "Genre".

### ISSUE THREAD

**Issue by AveDemid** [mdn/express-locallibrary-tutorial#72]
My bookController.js 

`const book_detail = (req, res, next) => {
  async.parallel(
    {
      book: function(callback) {
        Book.findById(req.params.id)
          .populate("author")
          .populate("genre")
          .exec(callback);
      },
      book_instance: function(callback) {
        BookInstance.find({ book: req.params.id }).exec(callback);
      }
    },
    function(err, results) {
      if (err) {
        return next(err);
      }
      if (results.book == null) {
        // No results.
        var err = new Error("Book not found");
        err.status = 404;
        return next(err);
      }
      // Successful, so render.
      res.render("book_detail", {
        title: "Title",
        book: results.book,
        book_instances: results.book_instance
      });
    }
  );
};
`

When i go to [http://localhost:3000/catalog/book/5d6bee7b04bf70aef9997566](url) i got error: Schema hasn't been registered for model "Genre". Use mongoose.model(name, schema)

`MissingSchemaError: Schema hasn't been registered for model "Genre".
Use mongoose.model(name, schema)
    at new MissingSchemaError (/Users/avedemid/Projects/local-library/node_modules/mongoose/lib/error/missingSchema.js:22:11)
    at NativeConnection.Connection.model (/Users/avedemid/Projects/local-library/node_modules/mongoose/lib/connection.js:946:11)
    at getModelsMapForPopulate (/Users/avedemid/Projects/local-library/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:198:59)
    at populate (/Users/avedemid/Projects/local-library/node_modules/mongoose/lib/model.js:4101:21)
    at _populate (/Users/avedemid/Projects/local-library/node_modules/mongoose/lib/model.js:4071:5)
    at /Users/avedemid/Projects/local-library/node_modules/mongoose/lib/model.js:4046:5
    at Object.promiseOrCallback (/Users/avedemid/Projects/local-library/node_modules/mongoose/lib/utils.js:249:12)
    at Function.Model.populate (/Users/avedemid/Projects/local-library/node_modules/mongoose/lib/model.js:4045:16)
    at model.Query.Query._completeOne (/Users/avedemid/Projects/local-library/node_modules/mongoose/lib/query.js:2033:9)
    at Immediate.<anonymous> (/Users/avedemid/Projects/local-library/node_modules/mongoose/lib/query.js:2072:10)
    at Immediate.<anonymous> (/Users/avedemid/Projects/local-library/node_modules/mquery/lib/utils.js:116:16)
    at processImmediate (internal/timers.js:439:21)`

And i really have no idea what the Genre has to do with it.

**Comment by AveDemid** [comment]
My bad, in model/genre.js i wrote `module.exports = mongoose.model("GenreSchema", GenreSchema);` instead `module.exports = mongoose.model("Genre", GenreSchema);`

**Comment by AveDemid** [comment]
My bad, in model/genre.js i wrote `module.exports = mongoose.model("GenreSchema", GenreSchema);` instead `module.exports = mongoose.model("Genre", GenreSchema);`
