### ISSUE TITLE
Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

### ISSUE THREAD

**Issue by j23saw** [mdn/express-locallibrary-tutorial#89]
```


exports.genre_detail = function(req, res, next) {
    var id = mongoose.Types.ObjectId(req.params.id); 
   
    async.parallel({
        genre: function(callback) {
            Genre.findById(id)
              .exec(callback);
        },

        genre_books: function(callback) {
            Book.find({ 'genre': id })
              .exec(callback);
        },

    }, function(err, results) {
        if (err) {
            console.log(req.params.id) 
            return next(err); }
        if (results.genre==null) { // No results.
            var err = new Error('Genre not found');
            err.status = 404;
            return next(err);
        }
        // Successful, so render
        res.render('genre_detail', { title: 'Genre Detail', genre: results.genre, genre_books: results.genre_books } );
    });
};

`





Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\bson\lib\bson\objectid.js:59:11)
    at ObjectID [as ObjectId] (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\bson\lib\bson\objectid.js:40:43)
    at exports.genre_detail (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\controllers\genreController.js:20:29)
    at Layer.handle [as handle_request] (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\express\lib\router\index.js:410:3)
    at next (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\JAYESH\Desktop\express-locallibrary-tutorial\node_modules\express\lib\router\index.js:317:13)

**Comment by hamishwillee** [comment]
Very likely :-)
1. Is this your code running or the example code in this repo.
2. Exactly what causes this? Just building, or entering a value somewhere. If so how do you get this?

**Comment by j23saw** [comment]
Thanks for fixing the formatting :) 
1. This is all of the example code running. No changes at all.

2. Before the present error, I was getting this error: `"Cast to ObjectId failed for value " undefined" at path "_id" for model "Genre"`. 
So instead of an actual ID, I'm getting an undefined value. I want to check the value of _req.params.id_ but I have no idea how to do so. Can you tell me how do i console log the value of _req.params.id_ ?

**Comment by hamishwillee** [comment]
Presumably the example code, but not with the package.json environment though. Because that works.

**Comment by j23saw** [comment]
That didn't help but I solved it nonetheless. Thanks for replying.
